### ISSUE TITLE
有一些规则未能正常出现

### ISSUE THREAD

**Issue by addre98** [Crystal0404/CrystalCarpetAddition#12]
### Bug description

我在一个1.20.6的服务器中正确安装了此mod（CrystalCarpetAddition-mc1.20.6-v1.4.0.jar）且已正常加载，/cca菜单中并未看到“重新引入旧版袭击(ReIntroduceOldVersionRaid)”和“重新引入旧版女巫战利品表(ReIntroduceOldVersionWitchLootTable)”规则，已经开启实验性快照

### Steps to reproduce

在1.20.6版本中安装本模组并进入已开启实验快照的存档（表现为杀死袭击队长掉落药且未获得不祥之兆），输入/cca list MCTweaks

### Expected behavior

列出包含ReIntroduceOldVersionRaid在内的多个选项

### Actual behavior

![image](https://github.com/Crystal0404/CrystalCarpetAddition/assets/111131309/a994d6fe-4eaf-4dbe-accd-a137c443a620)

_未包含ReIntroduceOldVersionRaid_

### Minecraft version

1.20.6

### CrystalCarpetAddition version

1.4.0

### Other information

modlist:

- architectury-12.1.3-fabric.jar
- carpet-extra-1.20.6-1.4.141.jar
- carpet-tis-addition-mc1.20.6-v1.60.1.jar
- cloth-config-14.0.126-fabric.jar
- collective-1.20.6-7.64.jar
- CrystalCarpetAddition-mc1.20.6-v1.4.0.jar        
- fabric-api-0.100.4+1.20.6.jar
- fabric-carpet-1.20.6-1.4.141+v240429.jar
- fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar   
- inventorytotem-1.20.6-3.2.jar
- Jade-1.20.6-Fabric-14.2.4.jar
- lithium-fabric-mc1.20.6-0.12.5.jar
- magiclib-all-0.7.398+fe2125a-stable.jar
- MCDRcommandFabric-1.20.4-v1.2.1.jar
- PluslsCarpetAddition-all-0.3.190+9e97daa-beta.jar
- quickshulker-1.4.3-1.20.6.jar
- servux-fabric-1.20.6-0.2.0.jar
- starlight-1.1.3+fabric.f5dcd1a.jar
- syncmatica-fabric-1.20.6-0.3.12-sakura.10.jar 

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [x] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Crystal0404** [comment]
女巫战利品表是在1.21快照修改的， 因此ReIntroduceOldVersionWitchLootTable不存在于1.20.6

ReIntroduceOldVersionRaid在1.20.6被移除了， 如果想体验1.21的新特性， 请游玩1.21.  

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年06月27日 22:50 |
| 收件人 | Crystal0404/CrystalCarpetAddition ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [Crystal0404/CrystalCarpetAddition] 有一些规则未能正常出现 (Issue #12) |

Bug description

我在一个1.20.6的服务器中正确安装了此mod（CrystalCarpetAddition-mc1.20.6-v1.4.0.jar）且已正常加载，/cca菜单中并未看到“重新引入旧版袭击(ReIntroduceOldVersionRaid)”和“重新引入旧版女巫战利品表(ReIntroduceOldVersionWitchLootTable)”规则，已经开启实验性快照

Steps to reproduce

在1.20.6版本中安装本模组并进入已开启实验快照的存档（表现为杀死袭击队长掉落药且未获得不祥之兆），输入/cca list MCTweaks

Expected behavior

列出包含ReIntroduceOldVersionRaid在内的多个选项

Actual behavior

image.png (view on web)
未包含ReIntroduceOldVersionRaid

Relevant logs

No response

Minecraft version

1.20.6

CrystalCarpetAddition version

1.4.0

Other information

modlist:

architectury-12.1.3-fabric.jar
carpet-extra-1.20.6-1.4.141.jar
carpet-tis-addition-mc1.20.6-v1.60.1.jar
cloth-config-14.0.126-fabric.jar
collective-1.20.6-7.64.jar
CrystalCarpetAddition-mc1.20.6-v1.4.0.jar
fabric-api-0.100.4+1.20.6.jar
fabric-carpet-1.20.6-1.4.141+v240429.jar
fabric-language-kotlin-1.11.0+kotlin.2.0.0.jar
inventorytotem-1.20.6-3.2.jar
Jade-1.20.6-Fabric-14.2.4.jar
lithium-fabric-mc1.20.6-0.12.5.jar
magiclib-all-0.7.398+fe2125a-stable.jar
MCDRcommandFabric-1.20.4-v1.2.1.jar
PluslsCarpetAddition-all-0.3.190+9e97daa-beta.jar
quickshulker-1.4.3-1.20.6.jar
servux-fabric-1.20.6-0.2.0.jar
starlight-1.1.3+fabric.f5dcd1a.jar
syncmatica-fabric-1.20.6-0.3.12-sakura.10.jar
Check list
I have verified that the issue persists in the latest version of the mod.
I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Crystal0404** [comment]
`ReIntroduceOldVersionRaid`会在`CCA-1.5.0`中重新引入

**Comment by Crystal0404** [comment]
`v1.5.0`已发布

**Comment by Crystal0404** [comment]
`1.6.0`中发生了一些变化

在`mc1.20.6`和`mc1.20.5`中, `ReIntroduceOldVersionRaid`被归入隐藏规则, 正常情况下它不会启用也不会出现在规则列表中. 如果你需要启用它, 请参阅 https://crystal0404.github.io/cca-doc/docs/HideSettings
